/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeneralResponseString } from '../../models/general-response-string';
import { MessageCreationRequest } from '../../models/message-creation-request';

export interface CreateMessage$Params {
      body: MessageCreationRequest
}

export function createMessage(http: HttpClient, rootUrl: string, params: CreateMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<GeneralResponseString>> {
  const rb = new RequestBuilder(rootUrl, createMessage.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeneralResponseString>;
    })
  );
}

createMessage.PATH = '/api/v1.0/message';
