/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatStatusRequest } from '../../models/chat-status-request';
import { GeneralResponseString } from '../../models/general-response-string';

export interface SetMessagesToSeen$Params {
      body: ChatStatusRequest
}

export function setMessagesToSeen(http: HttpClient, rootUrl: string, params: SetMessagesToSeen$Params, context?: HttpContext): Observable<StrictHttpResponse<GeneralResponseString>> {
  const rb = new RequestBuilder(rootUrl, setMessagesToSeen.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeneralResponseString>;
    })
  );
}

setMessagesToSeen.PATH = '/api/v1.0/message/seen';
