/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageInformationResponse } from '../models/message-information-response';
export interface GeneralResponseListMessageInformationResponse {
  data?: Array<MessageInformationResponse>;
  message?: string;
  status?: number;
}
