/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserInformationResponse } from '../models/user-information-response';
export interface GeneralResponseListUserInformationResponse {
  data?: Array<UserInformationResponse>;
  message?: string;
  status?: number;
}
