/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatInformationResponse } from '../models/chat-information-response';
export interface GeneralResponseListChatInformationResponse {
  data?: Array<ChatInformationResponse>;
  message?: string;
  status?: number;
}
