/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatCreatedResponse } from '../models/chat-created-response';
export interface GeneralResponseChatCreatedResponse {
  data?: ChatCreatedResponse;
  message?: string;
  status?: number;
}
