/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MediaMessageRequest {
  chatId?: string;
  content?: string;
  file?: string;
  nameFile?: string;
  senderId?: string;
}
