/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserInformationResponse {
  email?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  lastSeen?: string;
  online?: boolean;
}
