/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeneralResponseListUserInformationResponse } from '../../models/general-response-list-user-information-response';

export interface GetContacts$Params {
}

export function getContacts(http: HttpClient, rootUrl: string, params?: GetContacts$Params, context?: HttpContext): Observable<StrictHttpResponse<GeneralResponseListUserInformationResponse>> {
  const rb = new RequestBuilder(rootUrl, getContacts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeneralResponseListUserInformationResponse>;
    })
  );
}

getContacts.PATH = '/api/v1.0/users/contacts';
