/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GeneralResponseListUserInformationResponse } from '../models/general-response-list-user-information-response';
import { getContacts } from '../fn/user/get-contacts';
import { GetContacts$Params } from '../fn/user/get-contacts';


/**
 * User operations
 */
@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getContacts()` */
  static readonly GetContactsPath = '/api/v1.0/users/contacts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getContacts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContacts$Response(params?: GetContacts$Params, context?: HttpContext): Observable<StrictHttpResponse<GeneralResponseListUserInformationResponse>> {
    return getContacts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getContacts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContacts(params?: GetContacts$Params, context?: HttpContext): Observable<GeneralResponseListUserInformationResponse> {
    return this.getContacts$Response(params, context).pipe(
      map((r: StrictHttpResponse<GeneralResponseListUserInformationResponse>): GeneralResponseListUserInformationResponse => r.body)
    );
  }

}
